#!/usr/bin/env python3
"""
Build script for amplifier-webruntime.js

This script:
1. Takes wheel files and amplifier_webruntime.py
2. Encodes them as base64
3. Generates amplifier-webruntime.js with embedded assets

Usage:
    python scripts/build-bundle.py \
        --core-wheel /path/to/amplifier_core-X.X.X-py3-none-any.whl \
        --foundation-wheel /path/to/amplifier_foundation-X.X.X-py3-none-any.whl \
        --output dist/amplifier-webruntime.js

If wheel paths are not provided, the script will attempt to:
1. Build them from local repos (if available)
2. Download them from GitHub releases
"""

import argparse
import base64
import hashlib
import subprocess
import sys
import tempfile
from pathlib import Path

BUNDLE_ROOT = Path(__file__).parent.parent
SRC_DIR = BUNDLE_ROOT / "src"
JS_SRC = SRC_DIR / "js" / "amplifier-webruntime.src.js"
DIST_DIR = BUNDLE_ROOT / "dist"

VERSION = "0.1.0"


def compute_hash(content: bytes) -> str:
    """Compute short hash for verification."""
    return hashlib.sha256(content).hexdigest()[:8]


def encode_file(path: Path) -> tuple[str, str]:
    """Encode file to base64 and return (encoded, hash)."""
    content = path.read_bytes()
    encoded = base64.b64encode(content).decode("ascii")
    return encoded, compute_hash(content)


def find_or_build_wheel(
    package_name: str, local_repo: Path | None = None
) -> Path | None:
    """Find existing wheel or build from local repo."""

    # Check if we have a local repo
    if local_repo and local_repo.exists():
        print(f"Building {package_name} from {local_repo}...")

        # Build wheel using uv
        with tempfile.TemporaryDirectory() as tmpdir:
            result = subprocess.run(
                ["uv", "build", "--wheel", "--out-dir", tmpdir],
                cwd=local_repo,
                capture_output=True,
                text=True,
            )

            if result.returncode == 0:
                # Find the built wheel
                wheels = list(Path(tmpdir).glob("*.whl"))
                if wheels:
                    # Copy to dist
                    dest = DIST_DIR / wheels[0].name
                    dest.write_bytes(wheels[0].read_bytes())
                    print(f"  Built: {dest.name}")
                    return dest
            else:
                print(f"  Build failed: {result.stderr}")

    return None


def download_wheel(
    package_name: str, repo: str, version: str = "latest"
) -> Path | None:
    """Download wheel from GitHub releases."""
    # This is a placeholder - in practice you'd use GitHub API
    print(f"Downloading {package_name} wheel...")
    print("  (Download not implemented - please provide wheel path)")
    return None


def build_amplifier_webruntime_js(
    core_wheel: Path, foundation_wheel: Path, output: Path, minify: bool = False
) -> str:
    """Build the amplifier-webruntime.js file with embedded assets."""

    print("\nBuilding amplifier-webruntime.js...")

    # Read the JS source template
    if not JS_SRC.exists():
        raise FileNotFoundError(f"JS source not found: {JS_SRC}")

    js_template = JS_SRC.read_text()

    # Encode assets
    print("  Encoding assets...")

    # amplifier-core wheel
    core_b64, core_hash = encode_file(core_wheel)
    print(f"    amplifier-core.whl: {len(core_b64)} chars, hash={core_hash}")

    # amplifier-foundation wheel
    foundation_b64, foundation_hash = encode_file(foundation_wheel)
    print(
        f"    amplifier-foundation.whl: {len(foundation_b64)} chars, hash={foundation_hash}"
    )

    # amplifier_webruntime.py
    browser_py = SRC_DIR / "amplifier_webruntime.py"
    if not browser_py.exists():
        raise FileNotFoundError(f"Browser module not found: {browser_py}")

    browser_b64, browser_hash = encode_file(browser_py)
    print(f"    amplifier_webruntime.py: {len(browser_b64)} chars, hash={browser_hash}")

    # Replace placeholders in JS template
    js_content = js_template
    js_content = js_content.replace("%%AMPLIFIER_CORE_WHL%%", core_b64)
    js_content = js_content.replace("%%AMPLIFIER_CORE_WHL_FILENAME%%", core_wheel.name)
    js_content = js_content.replace("%%AMPLIFIER_FOUNDATION_WHL%%", foundation_b64)
    js_content = js_content.replace(
        "%%AMPLIFIER_FOUNDATION_WHL_FILENAME%%", foundation_wheel.name
    )
    js_content = js_content.replace("%%AMPLIFIER_WEBRUNTIME_PY%%", browser_b64)
    js_content = js_content.replace("%%VERSION%%", VERSION)

    # Add header comment
    header = f"""/**
 * amplifier-webruntime.js v{VERSION}
 * 
 * Browser-based Amplifier runtime with embedded assets.
 * 
 * Embedded assets (hashes for verification):
 *   amplifier-core.whl: {core_hash}
 *   amplifier-foundation.whl: {foundation_hash}
 *   amplifier_webruntime.py: {browser_hash}
 * 
 * Generated by: scripts/build-bundle.py
 * Do not edit directly - regenerate from source.
 */

"""

    js_content = header + js_content

    # Write output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(js_content)

    size_kb = len(js_content) / 1024
    print(f"\n  Output: {output}")
    print(f"  Size: {size_kb:.1f} KB")

    # Optionally minify
    if minify:
        print("  (Minification not implemented)")

    return js_content


def main():
    parser = argparse.ArgumentParser(
        description="Build amplifier-webruntime.js with embedded assets"
    )
    parser.add_argument(
        "--core-wheel", type=Path, help="Path to amplifier-core wheel file"
    )
    parser.add_argument(
        "--foundation-wheel", type=Path, help="Path to amplifier-foundation wheel file"
    )
    parser.add_argument(
        "--core-repo",
        type=Path,
        default=Path.home() / "repos" / "amplifier-core",
        help="Path to amplifier-core repo (for building wheel)",
    )
    parser.add_argument(
        "--foundation-repo",
        type=Path,
        default=Path.home() / "repos" / "amplifier-foundation",
        help="Path to amplifier-foundation repo (for building wheel)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DIST_DIR / "amplifier-webruntime.js",
        help="Output path for the JS bundle",
    )
    parser.add_argument("--minify", action="store_true", help="Minify the output JS")

    args = parser.parse_args()

    print("=" * 60)
    print("Building amplifier-webruntime.js")
    print("=" * 60)

    # Find or build core wheel
    core_wheel = args.core_wheel
    if not core_wheel or not core_wheel.exists():
        # Try to find existing wheel in dist
        existing = list(DIST_DIR.glob("amplifier_core-*.whl"))
        if existing:
            core_wheel = existing[0]
            print(f"Using existing core wheel: {core_wheel.name}")
        else:
            # Try to build from repo
            core_wheel = find_or_build_wheel("amplifier-core", args.core_repo)

    if not core_wheel or not core_wheel.exists():
        print("\nERROR: Could not find amplifier-core wheel.")
        print("Please provide --core-wheel or ensure --core-repo exists.")
        print("\nTo build manually:")
        print("  cd ~/repos/amplifier-core")
        print("  uv build --wheel")
        print("  cp dist/*.whl ~/repos/webllm-bundle/amplifier-bundle-browser/dist/")
        sys.exit(1)

    # Find or build foundation wheel
    foundation_wheel = args.foundation_wheel
    if not foundation_wheel or not foundation_wheel.exists():
        # Try to find existing wheel in dist
        existing = list(DIST_DIR.glob("amplifier_foundation-*.whl"))
        if existing:
            foundation_wheel = existing[0]
            print(f"Using existing foundation wheel: {foundation_wheel.name}")
        else:
            # Try to build from repo
            foundation_wheel = find_or_build_wheel(
                "amplifier-foundation", args.foundation_repo
            )

    if not foundation_wheel or not foundation_wheel.exists():
        print("\nERROR: Could not find amplifier-foundation wheel.")
        print("Please provide --foundation-wheel or ensure --foundation-repo exists.")
        print("\nTo build manually:")
        print("  cd ~/repos/amplifier-foundation")
        print("  uv build --wheel")
        print("  cp dist/*.whl ~/repos/webllm-bundle/amplifier-bundle-browser/dist/")
        sys.exit(1)

    # Build the JS bundle
    try:
        build_amplifier_webruntime_js(
            core_wheel=core_wheel,
            foundation_wheel=foundation_wheel,
            output=args.output,
            minify=args.minify,
        )
        print("\n✓ Build complete!")
        print("\nTo use, either:")
        print(f'  1. Include as script: <script src="{args.output.name}"></script>')
        print("  2. Inject into HTML: Copy contents into <script> tag")

    except Exception as e:
        print(f"\nERROR: Build failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
